name: Accessibility test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd AxeCICDIntegration
          npm install

      - name: Start app
        run: |
          cd AxeCICDIntegration
          npm start &
          sleep 10

      - name: Install Axe CLI
        run: npm install -g @axe-core/cli

      - name: Install matching Chrome + ChromeDriver
        run: npx browser-driver-manager install chrome

      - name: Run accessibility tests
        run: axe http://localhost:3000 --exit
